"""Declarative Authentik configuration for Mu3Lab.

The bootstrapper must not impersonate an operator in a browser or retain an
administrator password. Authentik's supported Blueprint mechanism gives us an
idempotent, atomic configuration boundary instead: the worker discovers this
file and creates the provider/application/outpost relationship itself.

Only non-secret, host-specific routing data is rendered here. OIDC client
secrets are intentionally not guessed; an app manifest must declare its exact
callback and secret hand-off before Mu3Lab creates one.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlsplit


_TAILNET_NAME = re.compile(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.ts\.net\Z")


def _quote(value: str) -> str:
    """Quote a validated plain value for the generated YAML."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _validate_host(host: str) -> str:
    host = host.rstrip(".")
    if not _TAILNET_NAME.fullmatch(host):
        raise ValueError("Authentik external host must be a MagicDNS ts.net name")
    return host


def _authentik_host(host: str, authentik_host: str | None) -> str:
    """Return the public Authentik origin used by the embedded outpost."""
    host = _validate_host(host)
    candidate = authentik_host or f"https://{host}:8444"
    parsed = urlsplit(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError("Authentik host must use a valid port") from exc
    if (parsed.scheme != "https" or parsed.hostname != host.lower() or
            port != 8444 or parsed.path not in ("", "/") or
            parsed.query or parsed.fragment or parsed.username or parsed.password):
        raise ValueError("Authentik host must be the private HTTPS :8444 origin")
    return f"https://{host}:8444"


def render_dashboard_blueprint(host: str, authentik_host: str | None = None) -> str:
    """Render the idempotent forward-auth setup for the Mu3Lab dashboard.

    The provider is deliberately forward-auth rather than proxy mode: Caddy
    remains responsible for serving the dashboard, while Authentik's embedded
    outpost handles authentication and returns identity headers to Caddy.
    """
    host = _validate_host(host)
    external = f"https://{host}"
    authentik_origin = _authentik_host(host, authentik_host)
    return f'''# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Generated by Mu3Lab. Do not edit in the checkout; the runtime copy is
# reconciled by Authentik's worker and contains no credentials.
version: 1
metadata:
  name: Mu3Lab dashboard access
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - model: authentik_providers_proxy.proxyprovider
    state: present
    identifiers:
      name: Mu3Lab dashboard provider
    attrs:
      name: Mu3Lab dashboard provider
      mode: forward_single
      external_host: {_quote(external)}
      access_token_validity: hours=24
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      intercept_header_auth: true
  - model: authentik_core.application
    state: present
    identifiers:
      slug: mu3lab
    attrs:
      name: Mu3Lab
      slug: mu3lab
      meta_launch_url: {_quote(external)}
      meta_description: Private Mu3Lab control plane
      policy_engine_mode: all
      provider: !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      name: authentik Embedded Outpost
      type: proxy
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
      config:
        authentik_host: {_quote(authentik_origin)}
        authentik_host_browser: {_quote(authentik_origin)}
'''


def write_dashboard_blueprint(runtime_root: Path, host: str,
                              authentik_host: str | None = None) -> Path:
    """Atomically write the runtime Blueprint and return its safe path.

    Authentik's worker watches this directory. Avoid replacing an identical
    file: duplicate watcher events can enqueue concurrent applies and make a
    harmless uniqueness race look like a failed Blueprint.
    """
    directory = runtime_root / "projects" / "authentik" / "blueprints"
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target = directory / "mu3lab-dashboard.yaml"
    content = render_dashboard_blueprint(host, authentik_host)
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        os.chmod(target, 0o600)
        return target
    temporary = target.with_suffix(".yaml.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, target)
    os.chmod(target, 0o600)
    return target
