"""Declarative Authentik configuration for Mu3Lab.

The bootstrapper must not impersonate an operator in a browser or retain an
administrator password. Authentik's supported Blueprint mechanism gives us an
idempotent, atomic configuration boundary instead: the worker discovers this
file and creates the provider/application/outpost relationship itself.

Only non-secret, host-specific routing data is rendered here. OIDC client
secrets are intentionally not guessed; an app manifest must declare its exact
callback and secret hand-off before Mu3Lab creates one.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlsplit


_TAILNET_NAME = re.compile(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.ts\.net\Z")


def _quote(value: str) -> str:
    """Quote a validated plain value for the generated YAML."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _validate_host(host: str) -> str:
    host = host.rstrip(".")
    if not _TAILNET_NAME.fullmatch(host):
        raise ValueError("Authentik external host must be a MagicDNS ts.net name")
    return host


def _authentik_host(host: str, authentik_host: str | None) -> str:
    """Return the public Authentik origin used by the embedded outpost."""
    host = _validate_host(host)
    candidate = authentik_host or f"https://{host}"
    parsed = urlsplit(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError("Authentik host must use a valid port") from exc
    if (parsed.scheme != "https" or parsed.hostname != host.lower() or
            port not in (None, 443) or parsed.path not in ("", "/") or
            parsed.query or parsed.fragment or parsed.username or parsed.password):
        raise ValueError("Authentik host must be the private standard-HTTPS origin")
    return f"https://{host}"


def _dashboard_host(host: str, dashboard_host: str | None) -> str:
    """Return the dashboard origin, deliberately separate from Authentik :443."""
    host = _validate_host(host)
    candidate = dashboard_host or f"https://{host}:8446"
    parsed = urlsplit(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError("Dashboard host must use a valid port") from exc
    if (parsed.scheme != "https" or parsed.hostname != host.lower() or
            port != 8446 or parsed.path not in ("", "/") or
            parsed.query or parsed.fragment or parsed.username or parsed.password):
        raise ValueError("Dashboard host must be the private HTTPS :8446 origin")
    return f"https://{host}:8446"


def render_dashboard_blueprint(host: str, authentik_host: str | None = None,
                               dashboard_host: str | None = None) -> str:
    """Render the idempotent forward-auth setup for the Mu3Lab dashboard.

    The provider is deliberately forward-auth rather than proxy mode: Caddy
    remains responsible for serving the dashboard, while Authentik's embedded
    outpost handles authentication and returns identity headers to Caddy.
    """
    host = _validate_host(host)
    external = _dashboard_host(host, dashboard_host)
    authentik_origin = _authentik_host(host, authentik_host)
    return f'''# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Generated by Mu3Lab. Do not edit in the checkout; the runtime copy is
# reconciled by Authentik's worker and contains no credentials.
version: 1
metadata:
  name: Mu3Lab dashboard access
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - model: authentik_core.group
    state: present
    identifiers:
      name: mu3lab-operators
    attrs:
      name: mu3lab-operators
  - model: authentik_providers_proxy.proxyprovider
    state: present
    identifiers:
      name: Mu3Lab dashboard provider
    attrs:
      name: Mu3Lab dashboard provider
      mode: forward_single
      external_host: {_quote(external)}
      access_token_validity: hours=24
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      intercept_header_auth: true
  - model: authentik_core.application
    id: mu3lab-dashboard-application
    state: present
    identifiers:
      slug: mu3lab
    attrs:
      name: Mu3Lab
      slug: mu3lab
      meta_launch_url: {_quote(external)}
      meta_description: Private Mu3Lab control plane
      policy_engine_mode: any
      provider: !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-dashboard-application
      order: 0
    attrs:
      group: !Find [authentik_core.group, [name, authentik Admins]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-dashboard-application
      order: 1
    attrs:
      group: !Find [authentik_core.group, [name, mu3lab-operators]]
  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      name: authentik Embedded Outpost
      type: proxy
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
      config:
        authentik_host: {_quote(authentik_origin)}
        authentik_host_browser: {_quote(authentik_origin)}
'''


def write_dashboard_blueprint(runtime_root: Path, host: str,
                              authentik_host: str | None = None,
                              dashboard_host: str | None = None) -> Path:
    """Atomically write the runtime Blueprint and return its safe path.

    Authentik's worker watches this directory. Avoid replacing an identical
    file: duplicate watcher events can enqueue concurrent applies and make a
    harmless uniqueness race look like a failed Blueprint.
    """
    directory = runtime_root / "projects" / "authentik" / "blueprints"
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target = directory / "mu3lab-dashboard.yaml"
    content = render_dashboard_blueprint(host, authentik_host, dashboard_host)
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        os.chmod(target, 0o600)
        return target
    temporary = target.with_suffix(".yaml.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, target)
    os.chmod(target, 0o600)
    return target


def render_open_webui_blueprint(host: str, client_id: str, client_secret: str) -> str:
    """Render the pinned Open WebUI OIDC provider and application."""
    host = _validate_host(host)
    if not client_id or not client_secret or any(char in client_id + client_secret for char in "\r\n"):
        raise ValueError("Open WebUI OIDC credentials are invalid")
    launch = f"https://{host}:8445"
    callback = f"{launch}/oauth/oidc/callback"
    return f'''# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Generated by Mu3Lab into root-excluded runtime storage.
version: 1
metadata:
  name: Mu3Lab Open WebUI OIDC
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - id: mu3lab-open-webui-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      name: Mu3Lab Open WebUI provider
    attrs:
      name: Mu3Lab Open WebUI provider
      client_type: confidential
      client_id: {_quote(client_id)}
      client_secret: {_quote(client_secret)}
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      issuer_mode: per_provider
      include_claims_in_id_token: true
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      redirect_uris:
        - matching_mode: strict
          url: {_quote(callback)}
  - model: authentik_core.application
    id: mu3lab-open-webui-application
    state: present
    identifiers:
      slug: mu3lab-open-webui
    attrs:
      name: Open WebUI
      slug: mu3lab-open-webui
      provider: !KeyOf mu3lab-open-webui-provider
      meta_launch_url: {_quote(launch)}
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-open-webui-application
      order: 0
    attrs:
      group: !Find [authentik_core.group, [name, authentik Admins]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-open-webui-application
      order: 1
    attrs:
      group: !Find [authentik_core.group, [name, mu3lab-operators]]
'''


def write_open_webui_blueprint(runtime_root: Path, host: str,
                               client_id: str, client_secret: str) -> Path:
    """Atomically install Open WebUI's OIDC blueprint for Authentik."""
    directory = runtime_root / "projects" / "authentik" / "blueprints"
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target = directory / "mu3lab-open-webui.yaml"
    content = render_open_webui_blueprint(host, client_id, client_secret)
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        os.chmod(target, 0o600)
        return target
    temporary = target.with_suffix(".yaml.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, target)
    os.chmod(target, 0o600)
    return target
