"""Declarative Authentik configuration for Mu3Lab.

The bootstrapper must not impersonate an operator in a browser or retain an
administrator password. Authentik's supported Blueprint mechanism gives us an
idempotent, atomic configuration boundary instead: the worker discovers this
file and creates the provider/application/outpost relationship itself.

Only non-secret, host-specific routing data is rendered here. OIDC client
secrets are intentionally not guessed; an app manifest must declare its exact
callback and secret hand-off before Mu3Lab creates one.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlsplit


_TAILNET_NAME = re.compile(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.ts\.net\Z")


def _quote(value: str) -> str:
    """Quote a validated plain value for the generated YAML."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _validate_host(host: str) -> str:
    host = host.rstrip(".")
    if not _TAILNET_NAME.fullmatch(host):
        raise ValueError("Authentik external host must be a MagicDNS ts.net name")
    return host


def _authentik_host(host: str, authentik_host: str | None) -> str:
    """Return the public Authentik origin used by the embedded outpost."""
    host = _validate_host(host)
    candidate = authentik_host or f"https://{host}"
    parsed = urlsplit(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError("Authentik host must use a valid port") from exc
    if (parsed.scheme != "https" or parsed.hostname != host.lower() or
            port not in (None, 443) or parsed.path not in ("", "/") or
            parsed.query or parsed.fragment or parsed.username or parsed.password):
        raise ValueError("Authentik host must be the private standard-HTTPS origin")
    return f"https://{host}"


def _dashboard_host(host: str, dashboard_host: str | None) -> str:
    """Return the dashboard origin, deliberately separate from Authentik :443."""
    host = _validate_host(host)
    candidate = dashboard_host or f"https://{host}:8446"
    parsed = urlsplit(candidate)
    try:
        port = parsed.port
    except ValueError as exc:
        raise ValueError("Dashboard host must use a valid port") from exc
    if (parsed.scheme != "https" or parsed.hostname != host.lower() or
            port != 8446 or parsed.path not in ("", "/") or
            parsed.query or parsed.fragment or parsed.username or parsed.password):
        raise ValueError("Dashboard host must be the private HTTPS :8446 origin")
    return f"https://{host}:8446"


def render_dashboard_blueprint(host: str, authentik_host: str | None = None,
                               dashboard_host: str | None = None) -> str:
    """Render the idempotent forward-auth setup for the Mu3Lab dashboard.

    The provider is deliberately forward-auth rather than proxy mode: Caddy
    remains responsible for serving the dashboard, while Authentik's embedded
    outpost handles authentication and returns identity headers to Caddy.
    """
    host = _validate_host(host)
    launch_url = _dashboard_host(host, dashboard_host)
    authentik_origin = _authentik_host(host, authentik_host)
    return f'''# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Generated by Mu3Lab. Do not edit in the checkout; the runtime copy is
# reconciled by Authentik's worker and contains no credentials.
version: 1
metadata:
  name: Mu3Lab dashboard access
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - model: authentik_core.group
    state: present
    identifiers:
      name: mu3lab-operators
    attrs:
      name: mu3lab-operators
  - model: authentik_providers_proxy.proxyprovider
    state: present
    identifiers:
      name: Mu3Lab dashboard provider
    attrs:
      name: Mu3Lab dashboard provider
      mode: forward_single
      # Tailscale Serve forwards the dashboard request to Caddy with the
      # tailnet hostname as the upstream host. Keep the outpost matcher on
      # the hostname; the user-facing launch URL retains :8446 below.
      external_host: {_quote(authentik_origin)}
      access_token_validity: hours=24
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      # Nextcloud user_oidc uses the authorization-code grant. The implicit
      # consent flow rejects that grant in current Authentik releases.
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      intercept_header_auth: true
  - model: authentik_core.application
    id: mu3lab-dashboard-application
    state: present
    identifiers:
      slug: mu3lab
    attrs:
      name: Mu3Lab
      slug: mu3lab
      meta_launch_url: {_quote(launch_url)}
      meta_description: Private Mu3Lab control plane
      policy_engine_mode: any
      provider: !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-dashboard-application
      order: 0
    attrs:
      group: !Find [authentik_core.group, [name, authentik Admins]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-dashboard-application
      order: 1
    attrs:
      group: !Find [authentik_core.group, [name, mu3lab-operators]]
  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      name: authentik Embedded Outpost
      type: proxy
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, Mu3Lab dashboard provider]]
      config:
        authentik_host: {_quote(authentik_origin)}
        authentik_host_browser: {_quote(authentik_origin)}
'''


def write_dashboard_blueprint(runtime_root: Path, host: str,
                              authentik_host: str | None = None,
                              dashboard_host: str | None = None) -> Path:
    """Atomically write the runtime Blueprint and return its safe path.

    Authentik's worker watches this directory. Avoid replacing an identical
    file: duplicate watcher events can enqueue concurrent applies and make a
    harmless uniqueness race look like a failed Blueprint.
    """
    directory = runtime_root / "projects" / "authentik" / "blueprints"
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target = directory / "mu3lab-dashboard.yaml"
    content = render_dashboard_blueprint(host, authentik_host, dashboard_host)
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        os.chmod(target, 0o600)
        return target
    temporary = target.with_suffix(".yaml.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, target)
    os.chmod(target, 0o600)
    return target


def render_oidc_application_blueprint(host: str, *, service_id: str, name: str,
                                      private_port: int, client_id: str,
                                      client_secret: str,
                                      redirect_paths: tuple[str, ...]) -> str:
    """Render one curated optional application's confidential OIDC client."""
    host = _validate_host(host)
    if (not service_id.replace("-", "").isalnum() or not name or
            not 1024 <= private_port <= 65535 or not client_id or not client_secret or
            any(char in client_id + client_secret for char in "\r\n") or
            not redirect_paths or any(not path.startswith("/") for path in redirect_paths)):
        raise ValueError("optional application OIDC contract is invalid")
    launch = f"https://{host}:{private_port}"
    redirects = "\n".join(
        f"        - matching_mode: strict\n          url: {_quote(launch + path)}"
        for path in redirect_paths
    )
    return f'''# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Generated by Mu3Lab into root-excluded runtime storage.
version: 1
metadata:
  name: Mu3Lab {name} OIDC
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - id: mu3lab-{service_id}-claims
    model: authentik_providers_oauth2.scopemapping
    state: present
    identifiers:
      name: Mu3Lab {name} verified identity claims
    attrs:
      name: Mu3Lab {name} verified identity claims
      scope_name: profile
      description: Verified email, groups, and Mu3Lab operator role
      expression: |
        groups = [group.name for group in request.user.ak_groups.all()]
        return {{
          "email_verified": bool(request.user.email),
          "preferred_username": request.user.username,
          "name": request.user.name or request.user.username,
          "groups": groups,
          "mu3lab_role": "admin" if "mu3lab-operators" in groups or "authentik Admins" in groups else "user",
        }}
  - id: mu3lab-{service_id}-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      name: Mu3Lab {name} provider
    attrs:
      name: Mu3Lab {name} provider
      client_type: confidential
      grant_types:
        - authorization_code
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Internal JWT Certificate]]
      client_id: {_quote(client_id)}
      client_secret: {_quote(client_secret)}
      # Native OIDC clients use authorization code + PKCE.
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      issuer_mode: per_provider
      include_claims_in_id_token: true
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !KeyOf mu3lab-{service_id}-claims
      redirect_uris:
{redirects}
  - model: authentik_core.application
    id: mu3lab-{service_id}-application
    state: present
    identifiers:
      slug: mu3lab-{service_id}
    attrs:
      name: {_quote(name)}
      slug: mu3lab-{service_id}
      provider: !KeyOf mu3lab-{service_id}-provider
      meta_launch_url: {_quote(launch)}
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-{service_id}-application
      order: 0
    attrs:
      group: !Find [authentik_core.group, [name, authentik Admins]]
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !KeyOf mu3lab-{service_id}-application
      order: 1
    attrs:
      group: !Find [authentik_core.group, [name, mu3lab-operators]]
'''


def write_oidc_application_blueprint(runtime_root: Path, host: str, **contract) -> Path:
    """Atomically publish one curated optional-application OIDC blueprint."""
    content = render_oidc_application_blueprint(host, **contract)
    service_id = str(contract["service_id"])
    directory = runtime_root / "projects" / "authentik" / "blueprints"
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    target = directory / f"mu3lab-{service_id}.yaml"
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        os.chmod(target, 0o600)
        return target
    temporary = target.with_suffix(".yaml.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, target)
    os.chmod(target, 0o600)
    return target
