"""Seed the owner's Vaultwarden with Mu3Lab logins and provider sign-up entries.

The owner submits their Vaultwarden master password once; it is used in
memory for a single run and never persisted. The run is idempotent and
conservative:

* Items Mu3Lab generated (application logins) carry a ``mu3lab_id`` field.
  Re-running rotates their password only when Mu3Lab's copy changed.
* Sign-up entries for inference providers are create-only. Once the owner has
  used a generated password to register, Mu3Lab never overwrites it.
* An existing login for the same site, saved by the owner by hand, is left
  alone and no duplicate is created.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlsplit

from ctl.identity import authentik_only
from ctl.integrations.vaultwarden import MATCH_HOST, Login, VaultSession
from ctl.platform_apps import by_capability
from ctl.provider_catalog import PROVIDERS
from ctl.registry import Registry
from ctl.runtime import RuntimePaths
from ctl.secrets import read_runtime_env
from ctl.store import onboarding as onboarding_state
from ctl.store import workflows as workflow_secrets

VAULTWARDEN_LOCAL_URL = "http://127.0.0.1:8081"
# Two separate folders: logins for Mu3Lab's own apps, and sign-up entries for
# AI providers the owner registers with.
FOLDER = "Mu3Lab app logins"
PROVIDER_FOLDER = "Mu3Lab AI providers"
FREELLMAPI_ACCOUNT = "mu3lab-gateway@localhost.test"


@dataclass(frozen=True)
class DesiredItem:
    mu3lab_id: str
    name: str
    folder: str
    username: str
    uris: tuple[tuple[str, int | None], ...]
    password: str = ""
    notes: str = ""
    # Managed application credentials follow Mu3Lab's copy; provider
    # sign-up entries are written once and then belong to the owner.
    rotate: bool = False
    onboarding_service_id: str = ""


@dataclass
class SeedResult:
    created: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    saved_onboarding: list[str] = field(default_factory=list)

    def public(self) -> dict[str, Any]:
        return {
            "created": self.created,
            "updated": self.updated,
            "unchanged": self.unchanged,
            "skipped": self.skipped,
        }


def _origin(host: str, port: int | None) -> str:
    return f"https://{host}" if port in (None, 443) else f"https://{host}:{port}"


def desired_items(
    *,
    registry: Registry,
    host: str,
    owner_uid: str,
    username: str,
    email: str,
    authentik_password: str = "",
    paths: RuntimePaths = RuntimePaths(),
) -> list[DesiredItem]:
    items: list[DesiredItem] = []
    if host:
        authentik = registry.get(by_capability("identity_provider").id)
        items.append(
            DesiredItem(
                mu3lab_id="service:authentik",
                name="Authentik (Mu3Lab sign-in)",
                folder=FOLDER,
                username=username or email,
                password=authentik_password,
                uris=((_origin(host, authentik.private_https_port), MATCH_HOST),),
                notes="Your Mu3Lab sign-in. Sign in with your email address."
                if authentik_password
                else "Your single sign-on for Mu3Lab apps. Your password was never sent to Mu3Lab; "
                "let the browser extension save it the next time you sign in.",
            )
        )
        password = read_runtime_env(paths.projects / by_capability("provider_gateway").id / ".env").get(
            "FREELLMAPI_ADMIN_PASSWORD", ""
        )
        if password:
            freellmapi = registry.get(by_capability("provider_gateway").id)
            items.append(
                DesiredItem(
                    mu3lab_id="service:freellmapi",
                    name="FreeLLMAPI dashboard",
                    folder=FOLDER,
                    username=FREELLMAPI_ACCOUNT,
                    password=password,
                    uris=((_origin(host, freellmapi.private_https_port), MATCH_HOST),),
                    notes="Generated by Mu3Lab. Authentik guards this dashboard; this login unlocks it.",
                    rotate=True,
                )
            )
    for record in onboarding_state.pending_logins(owner_uid, paths):
        service_id = record["service_id"]
        if authentik_only(service_id):
            continue
        login_url = record.get("login_url", "")
        items.append(
            DesiredItem(
                mu3lab_id=f"service:{service_id}",
                name=registry.get(service_id).name,
                folder=FOLDER,
                username=record["login_username"],
                password=record["password"],
                uris=((login_url, MATCH_HOST),) if login_url else (),
                rotate=True,
                notes="Generated by Mu3Lab. Normal access uses Authentik where supported.",
                onboarding_service_id=service_id,
            )
        )
    for provider in PROVIDERS:
        if provider.account != "email" or not provider.signup_url:
            continue
        uris = tuple((url, None) for url in dict.fromkeys((provider.signup_url, provider.keys_url)) if url)
        items.append(
            DesiredItem(
                mu3lab_id=f"provider:{provider.id}",
                name=provider.name,
                folder=PROVIDER_FOLDER,
                username=email,
                password=workflow_secrets.generate_password(),
                uris=uris,
                notes=(
                    "Pre-generated by Mu3Lab for signing up. If the site offers "
                    '"Continue with Google/GitHub" you can use that instead. '
                    f"After signing up, create an API key at {provider.keys_url} and paste it into "
                    "Mu3Lab under Settings → AI providers."
                ),
            )
        )
    return items


def _site(uri: str, *, with_port: bool) -> str:
    parts = urlsplit(uri if "://" in uri else f"https://{uri}")
    hostname = (parts.hostname or "").lower()
    if with_port:
        return f"{hostname}:{parts.port or 443}"
    # Registrable-ish domain: the last two labels are enough for the curated
    # provider hosts (console.groq.com and groq.com are the same site).
    return ".".join(hostname.split(".")[-2:])


def _existing_for(item: DesiredItem, logins: list[Login]) -> tuple[Login | None, bool]:
    """Return (managed match, whether an unmanaged login already covers the site)."""
    managed = next((login for login in logins if login.mu3lab_id == item.mu3lab_id), None)
    if managed:
        return managed, False
    with_port = item.mu3lab_id.startswith("service:")
    wanted = {_site(uri, with_port=with_port) for uri, _match in item.uris}
    covered = any(_site(uri, with_port=with_port) in wanted for login in logins for uri in login.uris)
    return None, covered


def seed(session: VaultSession, items: list[DesiredItem]) -> SeedResult:
    result = SeedResult()
    folders, logins = session.sync()
    folder_ids = {folder.name: folder.id for folder in folders}
    for item in items:
        managed, covered = _existing_for(item, logins)
        if managed:
            current = session.decrypt_password(managed)
            if item.rotate and item.password and current != item.password:
                session.replace_password(managed, item.password)
                result.updated.append(item.name)
            else:
                result.unchanged.append(item.name)
        elif covered:
            result.skipped.append(item.name)
            continue
        else:
            if item.folder not in folder_ids:
                folder_ids[item.folder] = session.create_folder(item.folder).id
            session.create_login(
                name=item.name,
                folder_id=folder_ids[item.folder],
                username=item.username,
                password=item.password,
                uris=list(item.uris),
                notes=item.notes,
                fields={"mu3lab_id": item.mu3lab_id},
            )
            result.created.append(item.name)
        if item.onboarding_service_id:
            result.saved_onboarding.append(item.onboarding_service_id)
    return result
